[[data]]
cv_name = "preparequery"
cv_description = "Плагин преобразования запросов filter,sort"
ck_d_provider = "swift"
ck_d_plugin = "PrepareQuery"
cl_required = 1
cl_default = 0
cct_params = { }
ck_id = "PrepareQuery:swift"
cn_order = 1

[[data]]
cv_name = "preparequery"
cv_description = "Плагин преобразования запросов filter,sort"
ck_d_provider = "bfl"
ck_d_plugin = "PrepareQuery"
cl_required = 1
cl_default = 0
cct_params = { }
ck_id = "PrepareQuerybfl"
cn_order = 1

[[data]]
cv_name = "preparequery"
cv_description = "Плагин преобразования запросов filter,sort"
ck_d_provider = "meta"
ck_d_plugin = "PrepareQuery"
cl_required = 1
cl_default = 0
cct_params = { }
ck_id = "PrepareQuerymeta"
cn_order = 1

[[data]]
cv_name = "preparequery"
cv_description = "Плагин преобразования запросов filter,sort"
ck_d_provider = "uspo"
ck_d_plugin = "PrepareQuery"
cl_required = 1
cl_default = 0
cct_params = { }
ck_id = "PrepareQueryuspo"
cn_order = 1

[[data]]
cv_name = "printjasperserver"
ck_d_provider = "meta"
ck_d_plugin = "USPOIntegration"
cv_description = "Плагин печати"
cl_required = 0
cl_default = 0
ck_id = "TRdnORgtbfZQgUDg"
cn_order = 3

  [data.cct_params]
  urlReceiver = "http://192.168.154.47:8080/uspo-print-receiver"
  prefixPath = "/reportserverbfl-dev"
  exportUrl = "c821e316-173d-4f71-b6a5-6a16f3bde6b3"
  queryNotification = "MTAddNotification"

[[data]]
cv_name = "printjasperserver"
ck_d_provider = "bfl"
ck_d_plugin = "USPOIntegration"
cv_description = "Плагин печати"
cl_required = 0
cl_default = 0
ck_id = "VR5Ml7YjzeBNT80c"
cn_order = 3

  [data.cct_params]
  urlReceiver = "http://192.168.154.47:8080/uspo-print-receiver"
  prefixPath = "/reportserverbfl-dev"
  exportUrl = "c821e316-173d-4f71-b6a5-6a16f3bde6b3"
  queryNotification = "MTAddNotification"

[[data]]
cv_name = "printjasperserver"
ck_d_provider = "uspo"
ck_d_plugin = "USPOIntegration"
cv_description = "Плагин печати"
cl_required = 0
cl_default = 0
ck_id = "VR5Ml7YjzeUSPO"
cn_order = 3

  [data.cct_params]
  urlReceiver = "http://192.168.154.47:8080/uspo-print-receiver"
  prefixPath = "/reportserverbfl-dev"
  exportUrl = "c821e316-173d-4f71-b6a5-6a16f3bde6b3"
  queryNotification = "MTAddNotification"

[[data]]
cv_name = "extractrow"
cv_description = "Плагин распаковывания вложеного json"
ck_d_provider = "meta"
ck_d_plugin = "JsonRowColumnExtractor"
cl_required = 1
cl_default = 0
ck_id = "extractRowmeta"
cn_order = 2

  [data.cct_params]
  extractSingleColumn = true
  columns = "json,result"

[[data]]
cv_name = "extractrow"
cv_description = "Плагин распаковывания вложеного json"
ck_d_provider = "swift"
ck_d_plugin = "JsonRowColumnExtractor"
cl_required = 1
cl_default = 0
ck_id = "extractRowuspo"
cn_order = 2

  [data.cct_params]
  extractSingleColumn = true
  columns = "json,result"
[[data]]
[data."$$indexCreated"]
fieldName = "ck_id"
unique = true
sparse = false
