[[data]]
ck_id = "admingate"
cv_description = "Провайдер администрирования"
ck_d_plugin = "admingate"

  [data.cct_params]
  cvRiakUrl = "http://192.168.154.27:8080"
  cctBuckets = '{"reports":{"accessKeyId":"QMPFV8D7WEED_65D1SOJ","secretAccessKey":"rBEdnuNX1b1Yt0f_SWGsl-Iu1H2PkEZFCvitDQ=="},"module":{"accessKeyId":"VYBDS-M9UAXEA13OAZG8","secretAccessKey":"fLK_vaKQCd0i0lqKHpEVlmtQk37jKiI0Tywrmw=="}}'

[[data]]
ck_id = "auth"
cv_description = "Провайдер авторизации"
cl_autoload = true
ck_d_plugin = "CoreAuthPG"

  [data.cct_params]
  poolMax = 100
  connectString = "postgres://swift01:swift01@192.168.155.18:5432/swift02"

[[data]]
ck_id = "meta"
cv_description = "Провайдер работы с метаинформацией"
cl_autoload = true
ck_d_plugin = "OracleDb"

  [data.cct_params]
  core = true
  user = "s_mc"
  password = "s_mc"
  poolMin = 5
  poolMax = 100
  connectString = "(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=192.168.155.18)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=BFL)))"

[[data]]
ck_id = "pko-ch-st"
ck_d_plugin = "ProxyTransparent"
cv_description = "Загрузка файла"

  [data.cct_params]
  timeout = 72_000
  gateUrl = "http://192.168.154.47:8080/pko-gate/change_status"

[[data]]
ck_id = "pko-gate"
ck_d_plugin = "ProxyTransparent"
cv_description = "Загрузка файла"

  [data.cct_params]
  timeout = 72_000
  gateUrl = "http://192.168.154.47:8080/pko-gate/upload"

[[data]]
ck_id = "pko-gt-dlw"
ck_d_plugin = "ProxyTransparent"
cv_description = "Скачаивание реестра 1С для ПКО"

  [data.cct_params]
  timeout = 72_000
  gateUrl = "http://192.168.154.47:8080/pko-gate/download"

[[data]]
ck_id = "sample"
cv_description = "Провайдер работы с БФЛ"
cl_autoload = true
ck_d_plugin = "OracleDb"

  [data.cct_params]
  core = true
  user = "s_mc"
  password = "s_mc"
  poolMin = 5
  poolMax = 100
  connectString = "(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=192.168.155.18)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=BFL)))"

[[data]]
ck_id = "swift"
ck_d_plugin = "PostgreSQLDb"
cv_description = "Провайдер USPO"

  [data.cct_params]
  poolMax = 100
  connectString = "postgres://swift01:swift01@192.168.155.18:5432/swift02"

[[data]]
ck_id = "uspo"
ck_d_plugin = "PostgreSQLDb"
cv_description = "Провайдер USPO"

  [data.cct_params]
  poolMax = 100
  connectString = "postgres://postgres:postgres@192.168.155.81:5432/print_server"
[[data]]
[data."$$indexCreated"]
fieldName = "ck_id"
unique = true
sparse = false
