[[data]]
ck_id = "authreload"
cv_description = "Перезагрузка плагина auth"
cl_enable = true
ck_d_plugin = "ReloadProvider"
cv_cron = "0 0 2 * * *"

  [data.cct_params]
  providerName = "auth"
[[data]]
[data."$$indexCreated"]
fieldName = "ck_id"
unique = true
sparse = false
